-- Tabla BRANDS
CREATE TABLE BRANDS (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);

-- Tabla PRODUCTS
CREATE TABLE PRODUCTS (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description TEXT
);

-- Tabla PRICES
CREATE TABLE PRICES (
brand_id BIGINT NOT NULL,
product_id BIGINT NOT NULL,
price_list INT NOT NULL,
start_date TIMESTAMP NOT NULL,
end_date TIMESTAMP NOT NULL,
priority INT NOT NULL,
price DECIMAL(10, 2) NOT NULL,
currency VARCHAR(3) NOT NULL,
PRIMARY KEY (brand_id, product_id, price_list, priority),
FOREIGN KEY (brand_id) REFERENCES BRANDS(id),
FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);
